language: python
python:
    - "2.7"
install: 
    - ""
    - "pip install -r requirements.txt"
script: 
    - "sudo apt-get install spatialite-bin"
    - "nosetests --with-coverage"
after_success: coveralls
